import os
from openai import AzureOpenAI
import time
import logging
from opentelemetry import trace
from azure.ai.agents.telemetry import trace_function

from dotenv import load_dotenv
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)

# Get tracer for telemetry
tracer = trace.get_tracer(__name__)

# Retrieve credentials from .env file or environment
endpoint = os.getenv("gpt_endpoint")
deployment = os.getenv("gpt_deployment")
api_key = os.getenv("gpt_api_key")
api_version = os.getenv("gpt_api_version")

# Initialize Azure OpenAI client for GPT model
client = AzureOpenAI(
    azure_endpoint=endpoint,
    api_key=api_key,
    api_version=api_version,
)

@trace_function
def get_image_description(image_url):
    start_time = time.time()
    """
    Input:
        image_url (str): Full URL to the image file (e.g., JPG, PNG)

    Output:
        summary (str): A Markdown-formatted summary of the image content generated by GPT model
    """
    logger.info(f"Starting image analysis with phi-4 model for image: {image_url[:50]}...")

    # Prepare the full chat prompt with system and user messages
    chat_prompt = [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "You are a helpful assistant that summarizes image content using {image_url} in concise. Respond in Markdown."
                }
            ]
        },
        {"role": "user", "content": image_url}
    ]

    # Call Azure OpenAI chat API with phi-4 vision model
    logger.info(f"Calling phi-4 vision model (deployment: {deployment}) for image analysis")
    completion = client.chat.completions.create(
        model=deployment,
        messages=chat_prompt,
        max_completion_tokens=10000,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0,
        stop=None,
        stream=False
    )
    end_sum = time.time()
    execution_time = end_sum - start_time
    
    # Log structured data about the phi-4 call
    logger.info(
        f"Phi-4 image analysis completed",
        extra={
            "model": deployment,
            "execution_time_seconds": execution_time,
            "image_url": image_url[:100],
            "prompt_tokens": completion.usage.prompt_tokens if completion.usage else None,
            "completion_tokens": completion.usage.completion_tokens if completion.usage else None,
            "total_tokens": completion.usage.total_tokens if completion.usage else None,
        }
    )
    print(f"get_image_description Execution Time: {execution_time} seconds")
    # Return summary content
    return completion.choices[0].message.content
